### ISSUE TITLE
request code for `activitynet`

### ISSUE THREAD

**Issue by leftthomas** [layer6ai-labs/ASL#3]
@satyakrishnagorti @junweima @guangster I can't obtain the result for `activitynet` by using your code, what's the hyper-parameters for `activitynet`?

**Comment by junweima** [comment]
The hyperparameters details are in the implementation details section in our paper. We use the same K for both THUMOS14 and Activitynet1.2 experiments.

**Comment by leftthomas** [comment]
@junweima, but the same hyper-parameters can not obtain the reported results, only 9.3 mAP@AVG is achieved, and this makes the paper non-reproducible, you should provide the training code about `activitynet` to make sure the results proved to be credible.
